### ISSUE TITLE
Improve [Random] to use a custom mini browser

### ISSUE THREAD

**Issue by sepulzera** [ownrecipes/OwnRecipes#11]
The [Random] recipe function is not much useful for us. Usually you are searching for a course. If you are looking for a main course, you probably have to hit the [Random] multiple times to skip appetizers, desserts and such.

It would be way more convenient to go to a randomized mini browser page. There you would select the course (default: Main Course) and get displayed 6 randomized recipes for this course.

Maybe that could be enhanced later, f. e. to include another option to filter only seasonal recipes.

**Comment by Sarajiko** [comment]
@sepulzera. I added a filter for cuisine__slug and one for tag__slug too, just in case.
