### ISSUE TITLE
Recipe rating: Increase length limit for comment field

### ISSUE THREAD

**Issue by sepulzera** [ownrecipes/OwnRecipes#86]
For recipe ratings, field comment, the current character limit is 250. As a side note, this is the same limit as for titles.

Increase the character limit for comments, either 500 or maybe even 1000, to allow for descriptive comments.

**Comment by ASANIYAN** [comment]
Good day. Can you assign this to me?

**Comment by sepulzera** [comment]
My pleasure! As a starting point, have a look at the file `ownrecipes-api/v1/rating/models.py`. Do not forget to create the django migration file, and to reflect your change in the OpenAPI file `ownrecipes-api/docs/ownrecipes-api.json`. Let me know if you need more information.

**Comment by sepulzera** [comment]
@ASANIYAN Happy New Year! How is it going?

**Comment by Lominex** [comment]
Hey, Happy New Year,
can i give it a try?

**Comment by sepulzera** [comment]
@Lominex We should give @ASANIYAN some more time to at least react to my latest query. There are some more [good first issues](https://github.com/ownrecipes/OwnRecipes/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) that you could tackle, f. e. #56 and #58.

**Comment by sepulzera** [comment]
Implemented. Also added a warning and error, when the length limit (is about to be) exceeded.
